### ISSUE TITLE
Autosubscriber should not explicitly rely on props

### ISSUE THREAD

**Issue by serkandurusoy** [nyura123/firebase-nest#1]
The current implementation of autosubscriber tightly couples components with store getting passed as external prop and kind of makes it mandatory to either implemet getSubs and subscribeSubs on the component level, or create a HOC to do the same.

It would be a lot more flexible if getSubs and subsribeSubs were run without the explicit reliance on props such that both can access an instance of a store that's provided externally/directly.

Otherwise, this explicit requirement can be documented in both here and over at the mobx-firebase-store readme.

PS: Cool package!

**Comment by nyura123** [comment]
Hi @serkandurusoy ,
thanks!
I've been working on a new HOC in`firebase-nest-mobx-react` repo, maybe that will be more useful. It uses mobx Provider and inject, and allows you to do something like this:

```js
//..
const authStore = //...
const chatStore = new MobxFirebaseStore(firebase.database().ref());
const subscribeSubs = chatStore.subscribeSubs.bind(chatStore);
```

App renders:
```
          <Provider chatStore={chatStore}
                    authStore={authStore}
                    subscribeSubs={subscribeSubs}>
              <MessageList />
          </Provider>
```

```js
import { mobxFirebaseAutoSubscriber } from 'firebase-nest-mobx-react';

class MessageList extends React.Component {
//...
}

function mobxInject(allStores) {
    const {authStore, chatStore} = allStores;
    return {
        chatStore,                                                       //will be passed to MessageList
        subscribeSubs: allStores.subscribeSubs,
        getSubs: (props, state) => {
            //Subscriptions based on observable authStore.authUser() -- will be called
            //whenever the observable changes.
            return authStore.authUser() ? chatStore.allMsgsSubs().concat(chatStore.allUsersSubs()) : []
        }
    }
}

export default mobxFirebaseAutoSubscriber(mobxInject)(observer((MessageList)));
```

**Comment by serkandurusoy** [comment]
Oh yes, this is defnitely much cleaner! When do you plan on releasing it?

**Comment by serkandurusoy** [comment]
Hmm examining it further, I'm not quite sure I'm all for the "provider" approach due to the fact that it exposes all stores from top down and for most apps it would become the top level element right above react router perhpas.

It would be even more awesome if we could have a MobxFirebaseStore that serves a specific purpose and only gets initialized for a certain route or component tree and then get disposed when that component tree gets unmounted.

**Comment by nyura123** [comment]
The HOC's released in firebase-nest-mobx-react, the example's [here](https://github.com/nyura123/firebase-nest-mobx-react)

You could create your stores in the component at the root of your tree (like App already does in the example), and then pass it down to your auto-subscriber component via props (instead of using Provider+inject). 

App:

```js
getSubs = (props, state) => {
       //can use stores & MessageList's props, state
        return
            this.stores.authStore.authUser() ?
              this.stores.chatStore.allMsgsSubs().concat(this.stores.chatStore.allUsersSubs()) :
              [];
    }

    render() {
        const subscribeSubs = this.stores.chatStore.subscribeSubs.bind(this.stores.chatStore);
        return (
              <MessageList
                authStore={this.stores.authStore}
                chatStore={this.stores.chatStore}
                getSubs={this.getSubs}
                subscribeSubs={subscribeSubs}
              />
        )
    }
```

MessageList would then need to pass down stores to its children as needed, and can be wrapped like this (without inject)

```
export default mobxFirebaseAutoSubscriber()(observer(MessageList));
```

**Comment by serkandurusoy** [comment]
I was actually inclining towards a solution where the stores are not passed
down as props at all!

That was my intention all along. Such that, the store is hidden away behind
the HOC and the components are not even aware of their existence.

**Comment by nyura123** [comment]
I guess an example of what you have in mind would help :) 
Something has to access the store observable properties somehow, so I don't see how we can avoid having store-aware components. But you could separate them into smart (wrapped in subscriber/observer) and dumb (plain-data props) like redux's containers/components.
Getting data out of stores could happen inside `mobxInject(allStores)` like in my 1st comment, or inside the smart component's render.

**Comment by serkandurusoy** [comment]
Yep, in fact that's kind of similar to what I do at the moment.

I have a HOC that provides the store information to the wrapped dumb
component and it itself receives the store information as its static
defaultProps property

This way, none of the visual components has to be aware of the existence of
a store or a provider, it is just a magical thing that comes in with the
HOC whose job is to populate the props of the wrapped dumb component.
