### ISSUE TITLE
resolveFirebaseQuery using user.uid before defined

### ISSUE THREAD

**Issue by SteveEmmerich** [nyura123/firebase-nest#3]
Hi,

Is there a way to have the resolveFirebaseQuery re-run after the onAuthStateChanged call back? I have a store using your firebase mobx store package that sets the user when the callback happens and on first login the resolve function is called before I have a user logged in. Any suggestions?

**Comment by nyura123** [comment]
Are you trying to subscribe based on user/auth? If so, you could reference the user observable in a component's getSubs (and render). There's an example of using auth in firebase-nest-mobx-react, let me know if it helps.

**Comment by SteveEmmerich** [comment]
Yes I am trying to subscribe based on the user/auth, but I don't think referencing auth in getSubs will help me unless I can pass it down to resolveFirebaseQuery. I need to use the resolveFirebaseQuery Method with the user uid to preform my query. My store has ` constructor() {
    super(firebase.database().ref())
    firebase.auth().onAuthStateChanged((user) => {
      this.user = user
    })
  }
  resolveFirebaseQuery(sub) {
    return this.fb.child(sub.path).orderByChild('viewedBy/'+this.user.uid).equalTo(null).limitToLast(10)
  }`
 I am still pretty new to react and your libs and I am not using your new firebase-nest-mobx-react. I just don't have the time to refactor all of the code for it. 

So I have a component that is an observer and autoscriber. ` static getSubs(props, state) {
    return props.stores.matches.subs()
  }
  subscribeSubs(subs,props, state) {
    const { matches } = props.stores
    const { unsubscribe, promise} = matches.subscribeSubsWithPromise(subs)
    this.setState({fetching:true}, () => {
      promise.then(() => {
        this.setState({fetching: false, fetchError: null})
      }, (error) => {
        this.setState({fetching: false, fetchError: error})
      })
    })
    return unsubscribe
  }` these are my getSubs and subscribeSubs. generally modeled off of your examples. the Subs method from my match store looks like this `subs() {
    return [{
        subKey: 'matches',
        path: 'posts',
        asList: true
    }]
  }` I am calling getData on matches in the render method so it should update properly. On initial login the user is null and my query fails after a refresh however, the user is fine. Should I be doing something different to get the user? Also if there is a slack, discourse, or gitter that would be more appropriate for this conversation please let me know since it really isn't an issue with your lib.

**Comment by nyura123** [comment]
You could make your user property observable, and then access it inside the component's getSubs, something like this:

```js
static getSubs(props, state) {
 ...
if (!store.getUser()) {
  //Don't subscribe to data if user is not logged in
  return [];
}
//otherwise return appropriate subscribtions
}
```

For this to work with `autoSubscriber`, you also need to call your `store.getUser()` inside `render` so that the component re-renders and getSubs gets called after the user's logged in.
(If you migrated to firebase-next-mobx-react HOC then you would no longer need to access user in render)

I think this is a good place for the questions in case it's useful for someone else :)
